baseURL = 'https://deadwanderer.github.io/'
languageCode = 'en-us'
title = 'Plodding...'
theme = "bearcub"
copyright = "Anthony Fisher"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[markup]
[markup.highlight]
lineNos = false
#lineNumbersInTable = true
noClasses = true
#noClasses = false

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[params]
subtitle = "Never finished, always improving"
dateFmt = "Monday, January 2, 2006"
enableNextPrevPages = true
enableRelatedPages = true
description = "Sometimes I do a thing..."
themeStyle = "original"

[permalinks]
posts = "/:year/:month/:day/:title/"

[params.author]
name = "deadwanderer"
#email = "anthonyjessica822@gmail.com"
bio = "Sometimes I do a thing..."

[menu]
[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 1
#  [[menu.main]]
#   identifier = "projects"
#   name = "Projects"
#   url = "/projects/"
#   weight = 2
